pedsim_spawn_points: 
  - ["sp0", 35.824600, -3.460210, 0.0]

pedsim_waypoints:
  - ["wp0", 54.1454, -7.07308, 0.0]


pedsim_routes:
  - ["sp3", "wp0", "wp1", "wp2", "wp3", "wp4", "wp3", "sp8"]
  - ["sp3", "wp0", "wp1", "wp2", "wp3", "wp4", "wp3", "wp5", "wp6", "sp4"]